### ISSUE TITLE
VIDEO media_type deprecated

### ISSUE THREAD

**Issue by michaelsylva** [jstolpe/instagram-graph-api-php-sdk#12]
in the {ig_user}/media endpoint you can no longer use media_type='VIDEO' it now must be media_type='REELS' still with the video_url parameter.

**Comment by johanvelthuis** [comment]
Only  change needed is changing the const below, Justin, could you please change this. Then we don't need to fork your repository. 

```
class MediaTypes {
    const VIDEO = 'REELS';
    const CAROUSEL = 'CAROUSEL';
}
```

**Comment by jstolpe** [comment]
updates for reels and stories are in release v1.0.6 thanks for pointing this out!
