### ISSUE TITLE
app version

### ISSUE THREAD

**Issue by abelr22** [jstolpe/instagram-graph-api-php-sdk#18]
Not issue, just a question. Your sdk is awesome. I just want to know where i can update the app version.  currently it post to https://graph.facebook.com/v14.0/{ig-id}/media_publish. i want to update it from v14.0 to the current version.

**Comment by jstolpe** [comment]
Thanks and glad to hear you are using the sdk! You can override the default graph version of "v14.0" in the config array that you pass in on instantiation. Here is an example:

$config = array( // instantiation config params
    'user_id' => '<IG_USER_ID>',
    'access_token' => '<ACCESS_TOKEN>',
    'graph_version' => '<GRAPH_VERSION>' // ADD THIS TO YOUR CONFIG TO OVERRIDE GRAPH VERSION
);
