### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by ahmadharminto** [jstolpe/instagram-graph-api-php-sdk#3]
Is it support PHP8 with composer installation?

**Comment by jstolpe** [comment]
I have not tested with PHP 8 yet but I will put it on my todo list, thanks!

**Comment by febryntara** [comment]
Package jstolpe/instagram-graph-api-php-sdk has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - jstolpe/instagram-graph-api-php-sdk v1.0.4 requires php ^5.6|^7.0 which does not match your installed version 8.1.6.
    
it doesnt support php 8 i think

**Comment by jstolpe** [comment]
I added php 8 to composer.json so it should work now.
